// Kumpulan ayat Al-Qur'an yang dipilih berdasarkan suasana hati.
// Setiap entri: { arab, latin, terjemah, surah, ayat, refleksi }

export const MOODS = [
  { id: 'happy',    emoji: '😄', label: 'Bahagia',   color: 'lemon' },
  { id: 'grateful', emoji: '🤍', label: 'Bersyukur', color: 'mint' },
  { id: 'sad',      emoji: '😔', label: 'Sedih',     color: 'sky' },
  { id: 'anxious',  emoji: '😟', label: 'Cemas',     color: 'lilac' },
  { id: 'tired',    emoji: '😴', label: 'Lelah',     color: 'sky' },
  { id: 'angry',    emoji: '😤', label: 'Marah',     color: 'rose' },
  { id: 'hopeful',  emoji: '✨', label: 'Penuh harap', color: 'lemon' },
  { id: 'lonely',   emoji: '🌙', label: 'Sendirian', color: 'lilac' },
]

export const QURAN_BY_MOOD = {
  happy: [
    {
      arab: 'قُلْ بِفَضْلِ اللَّهِ وَبِرَحْمَتِهِ فَبِذَٰلِكَ فَلْيَفْرَحُوا',
      latin: 'Qul bi fadhlillahi wa bi rahmatihi fa bi dzalika falyafrahu',
      terjemah: 'Katakanlah: "Dengan karunia Allah dan rahmat-Nya, hendaklah dengan itu mereka bergembira."',
      surah: 'Yunus', ayat: 58,
      refleksi: 'Bahagiamu hari ini adalah karunia. Nikmati sambil mensyukuri pemberinya.',
    },
    {
      arab: 'وَأَمَّا بِنِعْمَةِ رَبِّكَ فَحَدِّثْ',
      latin: 'Wa amma bini\'mati rabbika fa haddits',
      terjemah: 'Dan terhadap nikmat Tuhanmu, hendaklah engkau menceritakannya (dengan bersyukur).',
      surah: 'Adh-Dhuha', ayat: 11,
      refleksi: 'Ceritakan kebahagiaanmu — bukan untuk pamer, tapi sebagai bentuk syukur.',
    },
    {
      arab: 'وَرَفَعْنَا لَكَ ذِكْرَكَ',
      latin: 'Wa rafa\'na laka dzikrak',
      terjemah: 'Dan Kami tinggikan bagimu sebutan (nama)mu.',
      surah: 'Al-Insyirah', ayat: 4,
      refleksi: 'Kamu bahkan tidak tahu seberapa harum namamu di sisi-Nya hari ini.',
    },
    {
      arab: 'لَقَدْ خَلَقْنَا الْإِنسَانَ فِي أَحْسَنِ تَقْوِيمٍ',
      latin: 'Laqad khalaqnal insana fi ahsani taqwim',
      terjemah: 'Sesungguhnya Kami telah menciptakan manusia dalam bentuk yang sebaik-baiknya.',
      surah: 'At-Tin', ayat: 4,
      refleksi: 'Senyummu hari ini adalah bagian dari ciptaan terbaik. Pakai untuk menularkan kebaikan.',
    },
    {
      arab: 'فَبِأَيِّ آلَاءِ رَبِّكُمَا تُكَذِّبَانِ',
      latin: 'Fa bi ayyi alaa-i rabbikuma tukadzdziban',
      terjemah: 'Maka nikmat Tuhanmu yang manakah yang kamu dustakan?',
      surah: 'Ar-Rahman', ayat: 13,
      refleksi: 'Coba hitung — udara, mata, tawa, kopi pagi. Semua hadiah yang sering lupa diakui.',
    },
    {
      arab: 'وَهُوَ الَّذِي يَقْبَلُ التَّوْبَةَ عَنْ عِبَادِهِ',
      latin: 'Wa huwalladzi yaqbalut taubata \'an \'ibadih',
      terjemah: 'Dan Dialah yang menerima taubat dari hamba-hamba-Nya.',
      surah: 'Asy-Syura', ayat: 25,
      refleksi: 'Bahagia bukan tanda kamu sempurna — tapi tanda kamu dicintai apa adanya.',
    },
    {
      arab: 'وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَىٰ',
      latin: 'Wa lasaufa yu\'thika rabbuka fa tardha',
      terjemah: 'Dan kelak Tuhanmu pasti memberikan karunia-Nya kepadamu, lalu (hati)mu menjadi puas.',
      surah: 'Adh-Dhuha', ayat: 5,
      refleksi: 'Yang kamu rasakan sekarang baru sebagian. Yang terbaik masih dalam perjalanan.',
    },
    {
      arab: 'وَاللَّهُ يُحِبُّ الْمُحْسِنِينَ',
      latin: 'Wallahu yuhibbul muhsinin',
      terjemah: 'Dan Allah menyukai orang-orang yang berbuat kebaikan.',
      surah: 'Al-Baqarah', ayat: 195,
      refleksi: 'Hari yang baik dimulai dari hati yang ingin berbuat baik. Jaga itu.',
    },
    {
      arab: 'الَّذِينَ آمَنُوا وَتَطْمَئِنُّ قُلُوبُهُم بِذِكْرِ اللَّهِ',
      latin: 'Alladzina amanu wa tathma\'innu qulubuhum bi dzikrillah',
      terjemah: 'Yaitu orang-orang yang beriman dan hati mereka menjadi tenteram dengan mengingat Allah.',
      surah: 'Ar-Ra\'d', ayat: 28,
      refleksi: 'Bahagia paling stabil itu yang berakar pada-Nya, bukan pada keadaan.',
    },
    {
      arab: 'وَإِن تَعُدُّوا نِعْمَةَ اللَّهِ لَا تُحْصُوهَا',
      latin: 'Wa in ta\'uddu ni\'matallahi la tuhshuha',
      terjemah: 'Dan jika kamu menghitung nikmat Allah, niscaya kamu tidak akan mampu menghitungnya.',
      surah: 'An-Nahl', ayat: 18,
      refleksi: 'Kebahagiaan itu sebenarnya banyak — tinggal kita yang sering lupa menengok.',
    },
    {
      arab: 'إِنَّ اللَّهَ لَذُو فَضْلٍ عَلَى النَّاسِ',
      latin: 'Innallaha la dzu fadhlin \'alan nas',
      terjemah: 'Sesungguhnya Allah benar-benar mempunyai karunia atas seluruh manusia.',
      surah: 'Al-Baqarah', ayat: 243,
      refleksi: 'Semua orang punya sumber bahagia masing-masing. Hari ini, sumbermu sedang aktif.',
    },
    {
      arab: 'وَهُوَ الَّذِي خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ بِالْحَقِّ',
      latin: 'Wa huwalladzi khalaqas samawati wal ardha bil haqq',
      terjemah: 'Dan Dialah yang menciptakan langit dan bumi dengan benar.',
      surah: 'Al-An\'am', ayat: 73,
      refleksi: 'Langit yang sama yang melindungi nabi-nabi, melindungimu juga hari ini.',
    },
  ],
  grateful: [
    {
      arab: 'لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ',
      latin: 'La in syakartum la-azidannakum',
      terjemah: 'Sesungguhnya jika kamu bersyukur, pasti Aku akan menambah (nikmat) kepadamu.',
      surah: 'Ibrahim', ayat: 7,
      refleksi: 'Syukur adalah pintu yang membuka pintu-pintu lain.',
    },
    {
      arab: 'فَاذْكُرُونِي أَذْكُرْكُمْ وَاشْكُرُوا لِي وَلَا تَكْفُرُونِ',
      latin: 'Fadzkuruni adzkurkum wasykuru li wa la takfurun',
      terjemah: 'Maka ingatlah kepada-Ku, niscaya Aku ingat (pula) kepadamu, dan bersyukurlah kepada-Ku, dan janganlah kamu mengingkari (nikmat)-Ku.',
      surah: 'Al-Baqarah', ayat: 152,
      refleksi: 'Mengingat-Nya adalah cara paling lembut untuk merasa diingat.',
    },
    {
      arab: 'وَمَن شَكَرَ فَإِنَّمَا يَشْكُرُ لِنَفْسِهِ',
      latin: 'Wa man syakara fa innama yasykuru linafsih',
      terjemah: 'Dan barangsiapa yang bersyukur, sesungguhnya ia bersyukur untuk dirinya sendiri.',
      surah: 'An-Naml', ayat: 40,
      refleksi: 'Syukurmu tidak menambah apa-apa pada-Nya — tapi menambah ketenangan di hatimu.',
    },
    {
      arab: 'وَكُلُوا مِمَّا رَزَقَكُمُ اللَّهُ حَلَالًا طَيِّبًا',
      latin: 'Wa kulu mimma razaqakumullahu halalan thayyiba',
      terjemah: 'Dan makanlah dari apa yang telah Allah rezekikan kepadamu sebagai makanan yang halal lagi baik.',
      surah: 'Al-Maidah', ayat: 88,
      refleksi: 'Makanan di piringmu hari ini — itu juga jawaban dari doa yang dulu pernah kamu lupakan.',
    },
    {
      arab: 'وَإِذْ تَأَذَّنَ رَبُّكُمْ لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ',
      latin: 'Wa idz ta\'adzdzana rabbukum la in syakartum la-azidannakum',
      terjemah: 'Dan (ingatlah) ketika Tuhanmu memaklumkan: sungguh jika kamu bersyukur, pasti Aku akan menambah nikmat kepadamu.',
      surah: 'Ibrahim', ayat: 7,
      refleksi: 'Janji-Nya pasti. Syukur sekarang = pintu rezeki esok.',
    },
    {
      arab: 'وَآتَاكُم مِّن كُلِّ مَا سَأَلْتُمُوهُ',
      latin: 'Wa ataakum min kulli ma sa\'altumuh',
      terjemah: 'Dan Dia memberikan kepadamu (keperluanmu) dari segala apa yang kamu mohonkan kepada-Nya.',
      surah: 'Ibrahim', ayat: 34,
      refleksi: 'Banyak doa kecilmu yang sudah dijawab — sebelum kamu sempat sadar diijabahnya.',
    },
    {
      arab: 'فَكُلُوا مِمَّا رَزَقَكُمُ اللَّهُ حَلَالًا طَيِّبًا وَاشْكُرُوا نِعْمَتَ اللَّهِ',
      latin: 'Fakulu mimma razaqakumullahu halalan thayyiban wasykuru ni\'matallah',
      terjemah: 'Maka makanlah yang halal lagi baik dari rezeki yang telah diberikan Allah kepadamu, dan syukurilah nikmat Allah.',
      surah: 'An-Nahl', ayat: 114,
      refleksi: 'Tubuh ini titipan. Cara paling sederhana bersyukur adalah merawatnya.',
    },
    {
      arab: 'وَأَسْبَغَ عَلَيْكُمْ نِعَمَهُ ظَاهِرَةً وَبَاطِنَةً',
      latin: 'Wa asbagha \'alaikum ni\'amahu zhahiratan wa bathinah',
      terjemah: 'Dan menyempurnakan untukmu nikmat-Nya lahir dan batin.',
      surah: 'Luqman', ayat: 20,
      refleksi: 'Yang terlihat (kesehatan, rezeki) dan yang tak terlihat (iman, ketenangan) — keduanya hadiah.',
    },
    {
      arab: 'وَهُوَ الَّذِي يَقْبَلُ التَّوْبَةَ عَنْ عِبَادِهِ وَيَعْفُو عَنِ السَّيِّئَاتِ',
      latin: 'Wa huwalladzi yaqbalut taubata \'an \'ibadihi wa ya\'fu \'anis sayyi\'at',
      terjemah: 'Dan Dialah yang menerima taubat dari hamba-hamba-Nya dan memaafkan kesalahan-kesalahan.',
      surah: 'Asy-Syura', ayat: 25,
      refleksi: 'Diberi kesempatan untuk memperbaiki diri itu sendiri — sudah nikmat besar.',
    },
    {
      arab: 'إِنَّ رَبِّي لَطِيفٌ لِّمَا يَشَاءُ',
      latin: 'Inna rabbi lathifun lima yasya\'',
      terjemah: 'Sesungguhnya Tuhanku Maha Lembut terhadap apa yang Dia kehendaki.',
      surah: 'Yusuf', ayat: 100,
      refleksi: 'Cara-Nya menjawab doa kadang halus — kamu baru sadar setelah lama berlalu.',
    },
    {
      arab: 'الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ',
      latin: 'Alhamdu lillahi rabbil \'alamin',
      terjemah: 'Segala puji bagi Allah, Tuhan semesta alam.',
      surah: 'Al-Fatihah', ayat: 2,
      refleksi: 'Kalimat sederhana ini, kalau diucapkan dengan sadar, bisa mengubah seluruh hari.',
    },
  ],
  sad: [
    {
      arab: 'وَلَا تَهِنُوا وَلَا تَحْزَنُوا وَأَنتُمُ الْأَعْلَوْنَ إِن كُنتُم مُّؤْمِنِينَ',
      latin: 'Wa la tahinu wa la tahzanu wa antumul a\'launa in kuntum mu\'minin',
      terjemah: 'Janganlah kamu (merasa) lemah dan jangan (pula) bersedih hati, sebab kamu paling tinggi (derajatnya) jika kamu orang beriman.',
      surah: 'Ali Imran', ayat: 139,
      refleksi: 'Sedihmu valid, tapi imanmu lebih tinggi dari kesedihan itu.',
    },
    {
      arab: 'إِنَّ مَعَ الْعُسْرِ يُسْرًا',
      latin: 'Inna ma\'al \'usri yusra',
      terjemah: 'Sesungguhnya bersama kesulitan ada kemudahan.',
      surah: 'Al-Insyirah', ayat: 6,
      refleksi: 'Bukan setelah, tapi BERSAMA. Kemudahan itu sudah jalan, hanya belum kelihatan.',
    },
    {
      arab: 'لَا تَيْأَسُوا مِن رَّوْحِ اللَّهِ',
      latin: 'La tay\'asu min rauhillah',
      terjemah: 'Janganlah kamu berputus asa dari rahmat Allah.',
      surah: 'Yusuf', ayat: 87,
      refleksi: 'Selama nafas masih berhembus, harapan itu belum habis.',
    },
    {
      arab: 'إِنَّمَا أَشْكُو بَثِّي وَحُزْنِي إِلَى اللَّهِ',
      latin: 'Innama asyku batstsi wa huzni ilallah',
      terjemah: 'Sesungguhnya hanyalah kepada Allah aku mengadukan kesusahan dan kesedihanku.',
      surah: 'Yusuf', ayat: 86,
      refleksi: 'Boleh menangis. Boleh mengadu. Tapi adukan ke tempat yang paling tepat.',
    },
    {
      arab: 'وَلَنَبْلُوَنَّكُم بِشَيْءٍ مِّنَ الْخَوْفِ وَالْجُوعِ ۗ وَبَشِّرِ الصَّابِرِينَ',
      latin: 'Wa lanabluwannakum bi syai\'in minal khaufi wal ju\', wa basysyirish shabirin',
      terjemah: 'Dan sungguh akan Kami berikan cobaan kepadamu, dengan sedikit ketakutan, kelaparan... dan berikanlah berita gembira kepada orang-orang yang sabar.',
      surah: 'Al-Baqarah', ayat: 155,
      refleksi: 'Kesedihan ini bagian dari ujian yang akan kamu sabari — dan akan datang kabar baik.',
    },
    {
      arab: 'وَبَشِّرِ الصَّابِرِينَ ۝ الَّذِينَ إِذَا أَصَابَتْهُم مُّصِيبَةٌ قَالُوا إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ',
      latin: 'Wa basysyirish shabirin, alladzina idza ashabathum mushibatun qalu inna lillahi wa inna ilaihi raji\'un',
      terjemah: '...orang-orang yang apabila ditimpa musibah, mereka mengucapkan: "Sesungguhnya kami milik Allah dan kepada-Nya-lah kami kembali."',
      surah: 'Al-Baqarah', ayat: '155-156',
      refleksi: 'Kalimat ini menampung kesedihan paling berat — sambil mengembalikan semuanya pada-Nya.',
    },
    {
      arab: 'فَإِنَّ مَعَ الْعُسْرِ يُسْرًا',
      latin: 'Fa inna ma\'al \'usri yusra',
      terjemah: 'Maka sesungguhnya bersama kesulitan itu ada kemudahan.',
      surah: 'Al-Insyirah', ayat: 5,
      refleksi: 'Bukan setelah, tapi BERSAMA. Kemudahan itu ada di samping kesulitanmu sekarang.',
    },
    {
      arab: 'إِنَّ اللَّهَ مَعَ الصَّابِرِينَ',
      latin: 'Innallaha ma\'ash shabirin',
      terjemah: 'Sesungguhnya Allah beserta orang-orang yang sabar.',
      surah: 'Al-Baqarah', ayat: 153,
      refleksi: 'Sabar itu bukan diam — sabar itu ditemani oleh-Nya. Kamu tidak sendirian di titik ini.',
    },
    {
      arab: 'وَنُنَزِّلُ مِنَ الْقُرْآنِ مَا هُوَ شِفَاءٌ وَرَحْمَةٌ لِّلْمُؤْمِنِينَ',
      latin: 'Wa nunazzilu minal qur\'ani ma huwa syifa\'un wa rahmatun lil mu\'minin',
      terjemah: 'Dan Kami turunkan dari Al-Qur\'an sesuatu yang menjadi penyembuh dan rahmat bagi orang-orang yang beriman.',
      surah: 'Al-Isra', ayat: 82,
      refleksi: 'Kalau hatimu sedang sakit, bukalah Qur\'an — sekali pun cuma satu ayat. Itu obat.',
    },
    {
      arab: 'وَمَن يَتَّقِ اللَّهَ يَجْعَل لَّهُ مَخْرَجًا',
      latin: 'Wa man yattaqillaha yaj\'al lahu makhraja',
      terjemah: 'Barangsiapa bertakwa kepada Allah, niscaya Dia akan memberikan jalan keluar baginya.',
      surah: 'Ath-Thalaq', ayat: 2,
      refleksi: 'Pintu yang sekarang tertutup bukan satu-satunya pintu. Akan ada jalan.',
    },
    {
      arab: 'وَاللَّهُ خَيْرٌ حَافِظًا ۖ وَهُوَ أَرْحَمُ الرَّاحِمِينَ',
      latin: 'Wallahu khairun hafizhan, wa huwa arhamur rahimin',
      terjemah: 'Maka Allah adalah sebaik-baik penjaga, dan Dia adalah Maha Penyayang di antara para penyayang.',
      surah: 'Yusuf', ayat: 64,
      refleksi: 'Yang sedang menjagamu malam ini adalah Yang paling pengasih dari semua pengasih.',
    },
    {
      arab: 'وَلَا تَحْزَنْ إِنَّ اللَّهَ مَعَنَا',
      latin: 'Wa la tahzan innallaha ma\'ana',
      terjemah: 'Janganlah engkau bersedih, sesungguhnya Allah bersama kita.',
      surah: 'At-Taubah', ayat: 40,
      refleksi: 'Kata-kata Nabi ﷺ kepada Abu Bakar di gua. Kalimat yang sama berlaku untukmu malam ini.',
    },
    {
      arab: 'سَيَجْعَلُ اللَّهُ بَعْدَ عُسْرٍ يُسْرًا',
      latin: 'Sayaj\'alullahu ba\'da \'usrin yusra',
      terjemah: 'Allah kelak akan memberikan kemudahan setelah kesulitan.',
      surah: 'Ath-Thalaq', ayat: 7,
      refleksi: 'Janji ini bukan untuk orang lain — janji ini juga untukmu.',
    },
    {
      arab: 'وَلَنَجْزِيَنَّ الَّذِينَ صَبَرُوا أَجْرَهُم بِأَحْسَنِ مَا كَانُوا يَعْمَلُونَ',
      latin: 'Wa lanajziyannalladzina shabaru ajrahum bi ahsani ma kanu ya\'malun',
      terjemah: 'Dan sungguh akan Kami berikan balasan kepada orang-orang yang sabar dengan pahala yang lebih baik dari apa yang telah mereka kerjakan.',
      surah: 'An-Nahl', ayat: 96,
      refleksi: 'Air mata yang kamu jatuhkan diam-diam itu — tidak akan terbuang sia-sia.',
    },
  ],
  anxious: [
    {
      arab: 'أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ',
      latin: 'Ala bi dzikrillahi tathma\'innul qulub',
      terjemah: 'Ingatlah, hanya dengan mengingat Allah hati menjadi tenang.',
      surah: 'Ar-Ra\'d', ayat: 28,
      refleksi: 'Tarik napas. Sebut nama-Nya pelan-pelan. Tenangmu sedang dalam perjalanan.',
    },
    {
      arab: 'حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ',
      latin: 'Hasbunallahu wa ni\'mal wakil',
      terjemah: 'Cukuplah Allah (menjadi penolong) bagi kami dan Dia sebaik-baik pelindung.',
      surah: 'Ali Imran', ayat: 173,
      refleksi: 'Kamu tidak perlu memikul semuanya sendiri.',
    },
    {
      arab: 'لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا',
      latin: 'La yukallifullahu nafsan illa wus\'aha',
      terjemah: 'Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya.',
      surah: 'Al-Baqarah', ayat: 286,
      refleksi: 'Yang sedang kamu hadapi memang berat — tapi tidak melampaui kemampuanmu.',
    },
    {
      arab: 'وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ',
      latin: 'Wa man yatawakkal \'alallahi fa huwa hasbuh',
      terjemah: 'Dan barangsiapa bertawakal kepada Allah, niscaya Allah akan mencukupkan keperluannya.',
      surah: 'Ath-Thalaq', ayat: 3,
      refleksi: 'Lepaskan yang bukan urusanmu. Yang benar-benar penting akan dijaga oleh-Nya.',
    },
    {
      arab: 'إِنَّ مَعِيَ رَبِّي سَيَهْدِينِ',
      latin: 'Inna ma\'iya rabbi sayahdin',
      terjemah: 'Sesungguhnya Tuhanku bersamaku, Dia akan memberi petunjuk kepadaku.',
      surah: 'Asy-Syu\'ara', ayat: 62,
      refleksi: 'Kata Nabi Musa di tepi laut, dengan musuh di belakang. Petunjuk pasti datang.',
    },
    {
      arab: 'فَلَا تَخَافُوهُمْ وَخَافُونِ إِن كُنتُم مُّؤْمِنِينَ',
      latin: 'Fa la takhafuhum wa khafuni in kuntum mu\'minin',
      terjemah: 'Karena itu janganlah kamu takut kepada mereka, tetapi takutlah kepada-Ku, jika kamu orang-orang yang beriman.',
      surah: 'Ali Imran', ayat: 175,
      refleksi: 'Cemasmu pada manusia akan reda kalau hatimu cuma sandar pada-Nya.',
    },
    {
      arab: 'وَلَا تَهِنُوا فِي ابْتِغَاءِ الْقَوْمِ',
      latin: 'Wa la tahinu fibtigha\'il qaum',
      terjemah: 'Dan janganlah kamu berhati lemah dalam mengejar mereka.',
      surah: 'An-Nisa', ayat: 104,
      refleksi: 'Cemas itu wajar. Tapi jangan biarkan ia bikin kamu mundur dari hal yang penting.',
    },
    {
      arab: 'إِنَّ اللَّهَ يُحِبُّ الْمُتَوَكِّلِينَ',
      latin: 'Innallaha yuhibbul mutawakkilin',
      terjemah: 'Sesungguhnya Allah menyukai orang-orang yang bertawakal kepada-Nya.',
      surah: 'Ali Imran', ayat: 159,
      refleksi: 'Berserah itu bukan menyerah — itu memberi ruang pada-Nya untuk bekerja.',
    },
    {
      arab: 'فَإِنَّ اللَّهَ يَهْدِي مَن يَشَاءُ',
      latin: 'Fa innallaha yahdi man yasya\'',
      terjemah: 'Sesungguhnya Allah memberi petunjuk kepada siapa yang Dia kehendaki.',
      surah: 'Fathir', ayat: 8,
      refleksi: 'Yang kamu khawatirkan tentang masa depan — sudah ada petunjuk yang menanti di jalannya.',
    },
    {
      arab: 'وَإِن يَمْسَسْكَ اللَّهُ بِضُرٍّ فَلَا كَاشِفَ لَهُ إِلَّا هُوَ',
      latin: 'Wa in yamsaskallahu bi dhurrin fa la kasyifa lahu illa huwa',
      terjemah: 'Jika Allah menimpakan kemudaratan kepadamu, maka tidak ada yang dapat menghilangkannya selain Dia.',
      surah: 'Al-An\'am', ayat: 17,
      refleksi: 'Sumber masalah dan sumber solusi — keduanya hanya satu pintu. Datangi Dia.',
    },
    {
      arab: 'وَكَفَىٰ بِاللَّهِ وَكِيلًا',
      latin: 'Wa kafa billahi wakila',
      terjemah: 'Dan cukuplah Allah sebagai pelindung.',
      surah: 'An-Nisa', ayat: 81,
      refleksi: 'Yang lain bisa mengecewakan — Dia tidak. Sandar di tempat yang aman.',
    },
  ],
  tired: [
    {
      arab: 'فَإِنَّ مَعَ الْعُسْرِ يُسْرًا ۝ إِنَّ مَعَ الْعُسْرِ يُسْرًا',
      latin: 'Fa inna ma\'al \'usri yusra, inna ma\'al \'usri yusra',
      terjemah: 'Maka sesungguhnya bersama kesulitan ada kemudahan, sesungguhnya bersama kesulitan ada kemudahan.',
      surah: 'Al-Insyirah', ayat: '5-6',
      refleksi: 'Allah sebut dua kali. Lelahmu didengar. Istirahatlah dulu.',
    },
    {
      arab: 'وَجَعَلْنَا نَوْمَكُمْ سُبَاتًا',
      latin: 'Wa ja\'alna naumakum subata',
      terjemah: 'Dan Kami jadikan tidurmu untuk istirahat.',
      surah: 'An-Naba', ayat: 9,
      refleksi: 'Tidur bukan kelemahan — itu pemberian-Nya. Tidurlah dengan tenang.',
    },
    {
      arab: 'وَجَعَلْنَا اللَّيْلَ لِبَاسًا',
      latin: 'Wa ja\'alnal laila libasa',
      terjemah: 'Dan Kami jadikan malam sebagai pakaian.',
      surah: 'An-Naba', ayat: 10,
      refleksi: 'Malam ini, biarkan gelap menyelimutimu seperti pakaian. Lelahmu dipeluk.',
    },
    {
      arab: 'وَجَعَلْنَا النَّهَارَ مَعَاشًا',
      latin: 'Wa ja\'alnan nahara ma\'asya',
      terjemah: 'Dan Kami jadikan siang untuk mencari penghidupan.',
      surah: 'An-Naba', ayat: 11,
      refleksi: 'Lelahmu hari ini bukti kamu sudah menjalankan amanah. Layak rehat sekarang.',
    },
    {
      arab: 'لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا',
      latin: 'La yukallifullahu nafsan illa wus\'aha',
      terjemah: 'Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya.',
      surah: 'Al-Baqarah', ayat: 286,
      refleksi: 'Kamu tidak diberi beban yang tidak bisa kamu pikul. Yakini itu sambil rehat.',
    },
    {
      arab: 'وَهُوَ الَّذِي جَعَلَ لَكُمُ اللَّيْلَ لِبَاسًا وَالنَّوْمَ سُبَاتًا',
      latin: 'Wa huwalladzi ja\'ala lakumul laila libasaw wan nauma subata',
      terjemah: 'Dan Dialah yang menjadikan malam untukmu (sebagai) pakaian, dan tidur untuk istirahat.',
      surah: 'Al-Furqan', ayat: 47,
      refleksi: 'Bahkan tidurmu adalah ibadah, kalau diniatkan untuk siap kembali bekerja esok.',
    },
    {
      arab: 'يُرِيدُ اللَّهُ بِكُمُ الْيُسْرَ وَلَا يُرِيدُ بِكُمُ الْعُسْرَ',
      latin: 'Yuridullahu bikumul yusra wa la yuridu bikumul \'usr',
      terjemah: 'Allah menghendaki kemudahan bagimu, dan tidak menghendaki kesukaran bagimu.',
      surah: 'Al-Baqarah', ayat: 185,
      refleksi: 'Lelahmu bukan pertanda kamu salah jalan. Kadang lelah hanya karena kamu sayang sesuatu.',
    },
    {
      arab: 'وَهُوَ الَّذِي يَتَوَفَّاكُم بِاللَّيْلِ',
      latin: 'Wa huwalladzi yatawaffakum bil laili',
      terjemah: 'Dan Dialah yang menidurkan kamu di malam hari.',
      surah: 'Al-An\'am', ayat: 60,
      refleksi: 'Kamu tidak menidurkan dirimu sendiri — Dia yang menidurkan dengan lembut. Percayalah.',
    },
    {
      arab: 'وَلَا تَيْأَسُوا مِن رَّوْحِ اللَّهِ',
      latin: 'Wa la tay\'asu min rauhillah',
      terjemah: 'Dan janganlah kamu berputus asa dari rahmat Allah.',
      surah: 'Yusuf', ayat: 87,
      refleksi: 'Lelah boleh, putus asa jangan. Istirahat dulu, besok lanjut lagi.',
    },
    {
      arab: 'إِنَّ مَعَ الْعُسْرِ يُسْرًا',
      latin: 'Inna ma\'al \'usri yusra',
      terjemah: 'Sesungguhnya bersama kesulitan ada kemudahan.',
      surah: 'Al-Insyirah', ayat: 6,
      refleksi: 'Lelah hari ini sedang ditemani kemudahan yang belum kelihatan. Sabar sebentar.',
    },
    {
      arab: 'فَإِذَا فَرَغْتَ فَانصَبْ ۝ وَإِلَىٰ رَبِّكَ فَارْغَب',
      latin: 'Fa idza faraghta fanshab, wa ila rabbika farghab',
      terjemah: 'Maka apabila kamu telah selesai (dari sesuatu urusan), kerjakanlah dengan sungguh-sungguh (urusan) yang lain. Dan hanya kepada Tuhanmulah hendaknya kamu berharap.',
      surah: 'Al-Insyirah', ayat: '7-8',
      refleksi: 'Setelah satu lelah, akan ada lelah berikutnya — tapi semua bermuara pada-Nya.',
    },
  ],
  angry: [
    {
      arab: 'وَالْكَاظِمِينَ الْغَيْظَ وَالْعَافِينَ عَنِ النَّاسِ ۗ وَاللَّهُ يُحِبُّ الْمُحْسِنِينَ',
      latin: 'Wal kazhiminal ghaizha wal \'afina \'aninnas, wallahu yuhibbul muhsinin',
      terjemah: 'Dan orang-orang yang menahan amarahnya dan memaafkan (kesalahan) orang lain. Allah menyukai orang yang berbuat kebaikan.',
      surah: 'Ali Imran', ayat: 134,
      refleksi: 'Menahan marah hari ini adalah kemenangan kecil yang dilihat-Nya.',
    },
    {
      arab: 'ادْفَعْ بِالَّتِي هِيَ أَحْسَنُ',
      latin: 'Idfa\' billati hiya ahsan',
      terjemah: 'Tolaklah (kejahatan itu) dengan cara yang lebih baik.',
      surah: 'Fussilat', ayat: 34,
      refleksi: 'Balas dengan yang lebih baik — bukan untuk mereka, tapi untuk hatimu sendiri.',
    },
    {
      arab: 'وَإِذَا خَاطَبَهُمُ الْجَاهِلُونَ قَالُوا سَلَامًا',
      latin: 'Wa idza khathabahumul jahiluna qalu salama',
      terjemah: 'Dan apabila orang-orang jahil menyapa mereka, mereka mengucapkan kata-kata yang baik (salam).',
      surah: 'Al-Furqan', ayat: 63,
      refleksi: 'Cara paling elegan menanggapi sikap kasar — hanya dengan "salam." Damai pada dirimu.',
    },
    {
      arab: 'وَأَن تَعْفُوا أَقْرَبُ لِلتَّقْوَىٰ',
      latin: 'Wa an ta\'fu aqrabu littaqwa',
      terjemah: 'Dan memaafkan itu lebih dekat kepada takwa.',
      surah: 'Al-Baqarah', ayat: 237,
      refleksi: 'Memaafkan bukan untuk membebaskan mereka — tapi untuk memerdekakan dirimu.',
    },
    {
      arab: 'فَاعْفُ عَنْهُمْ وَاصْفَحْ ۚ إِنَّ اللَّهَ يُحِبُّ الْمُحْسِنِينَ',
      latin: 'Fa\'fu \'anhum washfah, innallaha yuhibbul muhsinin',
      terjemah: 'Maka maafkanlah mereka dan biarkanlah mereka, sesungguhnya Allah menyukai orang-orang yang berbuat baik.',
      surah: 'Al-Maidah', ayat: 13,
      refleksi: 'Lepaskan. Marahmu sudah didengar — sekarang serahkan urusannya pada-Nya.',
    },
    {
      arab: 'وَلَمَن صَبَرَ وَغَفَرَ إِنَّ ذَٰلِكَ لَمِنْ عَزْمِ الْأُمُورِ',
      latin: 'Wa laman shabara wa ghafara inna dzalika lamin \'azmil umur',
      terjemah: 'Tetapi orang yang bersabar dan memaafkan, sesungguhnya itu termasuk perbuatan yang utama.',
      surah: 'Asy-Syura', ayat: 43,
      refleksi: 'Marah itu mudah. Sabar dan memaafkan — itu yang besar.',
    },
    {
      arab: 'خُذِ الْعَفْوَ وَأْمُرْ بِالْعُرْفِ وَأَعْرِضْ عَنِ الْجَاهِلِينَ',
      latin: 'Khudzil \'afwa wa\'mur bil \'urfi wa a\'ridh \'anil jahilin',
      terjemah: 'Jadilah engkau pemaaf dan suruhlah orang mengerjakan yang ma\'ruf, serta berpalinglah dari orang-orang yang bodoh.',
      surah: 'Al-A\'raf', ayat: 199,
      refleksi: 'Tidak semua omongan layak dijawab. Berpaling itu juga bentuk kemenangan.',
    },
    {
      arab: 'وَجَزَاءُ سَيِّئَةٍ سَيِّئَةٌ مِّثْلُهَا ۖ فَمَنْ عَفَا وَأَصْلَحَ فَأَجْرُهُ عَلَى اللَّهِ',
      latin: 'Wa jaza\'u sayyi\'atin sayyi\'atum mitsluha, fa man \'afa wa ashlaha fa ajruhu \'alallah',
      terjemah: 'Balasan suatu kejahatan adalah kejahatan yang setimpal. Tetapi barangsiapa memaafkan dan berbuat baik, maka pahalanya atas (tanggungan) Allah.',
      surah: 'Asy-Syura', ayat: 40,
      refleksi: 'Kalau memilih untuk tidak membalas, jangan kira pahalamu hilang. Allah yang membayar.',
    },
    {
      arab: 'إِنَّ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ سَيَجْعَلُ لَهُمُ الرَّحْمَٰنُ وُدًّا',
      latin: 'Innalladzina amanu wa \'amilush shalihati sayaj\'alu lahumur rahmanu wudda',
      terjemah: 'Sesungguhnya orang-orang yang beriman dan beramal saleh, kelak Allah Yang Maha Pemurah akan menanamkan dalam (hati) mereka rasa kasih sayang.',
      surah: 'Maryam', ayat: 96,
      refleksi: 'Marah hari ini akan reda. Yang tinggal di hati orang adalah kebaikanmu.',
    },
    {
      arab: 'وَلَا تَسْتَوِي الْحَسَنَةُ وَلَا السَّيِّئَةُ ۚ ادْفَعْ بِالَّتِي هِيَ أَحْسَنُ',
      latin: 'Wa la tastawil hasanatu wa las sayyi\'ah, idfa\' billati hiya ahsan',
      terjemah: 'Dan tidaklah sama kebaikan dan kejahatan. Tolaklah (kejahatan itu) dengan cara yang lebih baik.',
      surah: 'Fussilat', ayat: 34,
      refleksi: 'Lawan keburukan dengan kebaikan — itu senjata paling melumpuhkan.',
    },
  ],
  hopeful: [
    {
      arab: 'وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ ۚ إِنَّ اللَّهَ بَالِغُ أَمْرِهِ',
      latin: 'Wa man yatawakkal \'alallahi fa huwa hasbuh, innallaha balighu amrih',
      terjemah: 'Dan barangsiapa bertawakal kepada Allah, niscaya Allah akan mencukupkan (keperluan)nya. Sesungguhnya Allah pasti melaksanakan urusan-Nya.',
      surah: 'Ath-Thalaq', ayat: 3,
      refleksi: 'Harapanmu didengar. Tugasmu hanya berusaha & berserah.',
    },
    {
      arab: 'وَعَسَىٰ أَن تَكْرَهُوا شَيْئًا وَهُوَ خَيْرٌ لَّكُمْ',
      latin: 'Wa \'asa an takrahu syai\'an wa huwa khairul lakum',
      terjemah: 'Boleh jadi kamu membenci sesuatu, padahal itu baik bagimu.',
      surah: 'Al-Baqarah', ayat: 216,
      refleksi: 'Yang belum sesuai harapanmu, mungkin sedang menyiapkan yang lebih baik.',
    },
    {
      arab: 'إِنَّ مَعَ الْعُسْرِ يُسْرًا',
      latin: 'Inna ma\'al \'usri yusra',
      terjemah: 'Sesungguhnya bersama kesulitan itu ada kemudahan.',
      surah: 'Al-Insyirah', ayat: 6,
      refleksi: 'Harapanmu valid. Kemudahan sudah dikirim — tinggal dalam perjalanan.',
    },
    {
      arab: 'وَبَشِّرِ الَّذِينَ آمَنُوا أَنَّ لَهُمْ قَدَمَ صِدْقٍ عِندَ رَبِّهِمْ',
      latin: 'Wa basysyirilladzina amanu anna lahum qadama shidqin \'inda rabbihim',
      terjemah: 'Dan berilah kabar gembira kepada orang-orang yang beriman, bahwa mereka mempunyai kedudukan yang tinggi di sisi Tuhan mereka.',
      surah: 'Yunus', ayat: 2,
      refleksi: 'Yang kamu kerjakan dalam diam — diingat-Nya, dan akan dibalas dengan tempat yang baik.',
    },
    {
      arab: 'إِنَّ اللَّهَ لَا يُضِيعُ أَجْرَ الْمُحْسِنِينَ',
      latin: 'Innallaha la yudhi\'u ajral muhsinin',
      terjemah: 'Sesungguhnya Allah tidak menyia-nyiakan pahala orang-orang yang berbuat baik.',
      surah: 'At-Taubah', ayat: 120,
      refleksi: 'Tidak ada usahamu yang sia-sia. Bahkan yang tidak terlihat orang lain — Dia melihat.',
    },
    {
      arab: 'وَلَا تَيْأَسُوا مِن رَّوْحِ اللَّهِ ۖ إِنَّهُ لَا يَيْأَسُ مِن رَّوْحِ اللَّهِ إِلَّا الْقَوْمُ الْكَافِرُونَ',
      latin: 'Wa la tay\'asu min rauhillah, innahu la yay\'asu min rauhillahi illal qaumul kafirun',
      terjemah: 'Dan janganlah kamu berputus asa dari rahmat Allah. Sesungguhnya tiada berputus asa dari rahmat Allah, melainkan kaum yang kafir.',
      surah: 'Yusuf', ayat: 87,
      refleksi: 'Selama kamu masih punya harapan, kamu masih beriman. Pegang erat-erat.',
    },
    {
      arab: 'إِنَّ رَحْمَتَ اللَّهِ قَرِيبٌ مِّنَ الْمُحْسِنِينَ',
      latin: 'Inna rahmatallahi qaribum minal muhsinin',
      terjemah: 'Sesungguhnya rahmat Allah amat dekat kepada orang-orang yang berbuat baik.',
      surah: 'Al-A\'raf', ayat: 56,
      refleksi: 'Rahmat-Nya bukan sesuatu yang jauh — ia berjalan bersamamu, dekat sekali.',
    },
    {
      arab: 'إِنَّ اللَّهَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
      latin: 'Innallaha \'ala kulli syai\'in qadir',
      terjemah: 'Sesungguhnya Allah Maha Kuasa atas segala sesuatu.',
      surah: 'Al-Baqarah', ayat: 20,
      refleksi: 'Yang sekarang terasa mustahil — buat-Nya hanya tinggal "Kun." Yakini.',
    },
    {
      arab: 'وَيَرْزُقْهُ مِنْ حَيْثُ لَا يَحْتَسِبُ',
      latin: 'Wa yarzuqhu min haitsu la yahtasib',
      terjemah: 'Dan Allah memberinya rezeki dari arah yang tiada disangka-sangkanya.',
      surah: 'Ath-Thalaq', ayat: 3,
      refleksi: 'Jawaban doa sering datang dari pintu yang kamu nggak pernah lihat sebelumnya.',
    },
    {
      arab: 'وَأَنَّ اللَّهَ هُوَ يُحْيِي الْمَوْتَىٰ وَأَنَّهُ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
      latin: 'Wa annallaha huwa yuhyil mauta wa annahu \'ala kulli syai\'in qadir',
      terjemah: 'Dan sesungguhnya Allah menghidupkan orang-orang yang ada di dalam kubur, dan sesungguhnya Dia Maha Kuasa atas segala sesuatu.',
      surah: 'Al-Hajj', ayat: 7,
      refleksi: 'Yang sudah mati pun dihidupkan-Nya. Mimpimu yang "mati" — bisa Dia hidupkan kembali.',
    },
    {
      arab: 'فَإِنَّ مَعَ الْعُسْرِ يُسْرًا ۝ إِنَّ مَعَ الْعُسْرِ يُسْرًا',
      latin: 'Fa inna ma\'al \'usri yusra, inna ma\'al \'usri yusra',
      terjemah: 'Maka sesungguhnya bersama kesulitan ada kemudahan, sesungguhnya bersama kesulitan ada kemudahan.',
      surah: 'Al-Insyirah', ayat: '5-6',
      refleksi: 'Allah ulangi dua kali — supaya kamu yakin. Yusra-mu sudah dekat.',
    },
  ],
  lonely: [
    {
      arab: 'وَنَحْنُ أَقْرَبُ إِلَيْهِ مِنْ حَبْلِ الْوَرِيدِ',
      latin: 'Wa nahnu aqrabu ilaihi min hablil warid',
      terjemah: 'Dan Kami lebih dekat kepadanya daripada urat lehernya sendiri.',
      surah: 'Qaf', ayat: 16,
      refleksi: 'Sekalipun semua orang menjauh, Dia tidak pernah pergi.',
    },
    {
      arab: 'إِنَّ اللَّهَ مَعَنَا',
      latin: 'Innallaha ma\'ana',
      terjemah: 'Sesungguhnya Allah bersama kita.',
      surah: 'At-Taubah', ayat: 40,
      refleksi: 'Sendiri tidak sama dengan sepi. Ada Yang selalu menemani.',
    },
    {
      arab: 'وَإِذَا سَأَلَكَ عِبَادِي عَنِّي فَإِنِّي قَرِيبٌ',
      latin: 'Wa idza sa\'alaka \'ibadi \'anni fa inni qarib',
      terjemah: 'Dan apabila hamba-hamba-Ku bertanya kepadamu tentang Aku, maka (jawablah) bahwa Aku adalah dekat.',
      surah: 'Al-Baqarah', ayat: 186,
      refleksi: 'Tidak ada perantara untuk berbicara dengan-Nya. Bisik saja, Dia mendengar.',
    },
    {
      arab: 'أُجِيبُ دَعْوَةَ الدَّاعِ إِذَا دَعَانِ',
      latin: 'Ujibu da\'watad da\'i idza da\'an',
      terjemah: 'Aku mengabulkan permohonan orang yang berdoa apabila ia berdoa kepada-Ku.',
      surah: 'Al-Baqarah', ayat: 186,
      refleksi: 'Doamu yang lirih malam ini — sampai. Tidak satu kata pun yang luput.',
    },
    {
      arab: 'وَكَانَ اللَّهُ بِكُلِّ شَيْءٍ مُّحِيطًا',
      latin: 'Wa kanallahu bi kulli syai\'in muhitha',
      terjemah: 'Dan adalah Allah Maha Meliputi segala sesuatu.',
      surah: 'An-Nisa', ayat: 126,
      refleksi: 'Kamu sedang dipeluk oleh Yang meliputi segalanya. Sendirian itu cuma rasa, bukan kenyataan.',
    },
    {
      arab: 'اللَّهُ وَلِيُّ الَّذِينَ آمَنُوا',
      latin: 'Allahu waliyyulladzina amanu',
      terjemah: 'Allah pelindung orang-orang yang beriman.',
      surah: 'Al-Baqarah', ayat: 257,
      refleksi: 'Pelindung paling setia bukan manusia — Dia, yang tidak pernah meninggalkanmu.',
    },
    {
      arab: 'وَهُوَ مَعَكُمْ أَيْنَ مَا كُنتُمْ',
      latin: 'Wa huwa ma\'akum ainama kuntum',
      terjemah: 'Dan Dia bersamamu di mana saja kamu berada.',
      surah: 'Al-Hadid', ayat: 4,
      refleksi: 'Di kamar kosongmu, di jalan ramai, di mana pun — Dia tidak pernah absen menemani.',
    },
    {
      arab: 'لَا تَخَافِي وَلَا تَحْزَنِي',
      latin: 'La takhafi wa la tahzani',
      terjemah: 'Janganlah engkau takut dan janganlah engkau bersedih hati.',
      surah: 'Al-Qashash', ayat: 7,
      refleksi: 'Kalimat lembut dari Allah kepada ibunda Musa — dan sekarang juga untukmu.',
    },
    {
      arab: 'فَإِنَّكَ بِأَعْيُنِنَا',
      latin: 'Fa innaka bi a\'yunina',
      terjemah: 'Sesungguhnya engkau berada dalam pengawasan Kami.',
      surah: 'Ath-Thur', ayat: 48,
      refleksi: 'Sekalipun tidak ada mata manusia yang melihatmu malam ini — mata-Nya tidak pernah tidur.',
    },
    {
      arab: 'وَكَفَىٰ بِاللَّهِ وَلِيًّا ۚ وَكَفَىٰ بِاللَّهِ نَصِيرًا',
      latin: 'Wa kafa billahi waliyya, wa kafa billahi nashira',
      terjemah: 'Dan cukuplah Allah menjadi pelindung dan cukuplah Allah menjadi penolong.',
      surah: 'An-Nisa', ayat: 45,
      refleksi: 'Saat manusia mengecewakan, Dia tetap cukup. Lebih dari cukup.',
    },
  ],
}

export function getQuoteForMood(moodId, seed = Date.now()) {
  const list = QURAN_BY_MOOD[moodId] || QURAN_BY_MOOD.hopeful
  const idx = Math.abs(Math.floor(seed / 1000)) % list.length
  return list[idx]
}
